### ISSUE TITLE
Routeros 7

### ISSUE THREAD

**Issue by mglants** [oGi4i/mikrotik-exporter#11]
BGP collector not working
`{"collector":"bgp_session","device":"mikrotik","error":"failed to fetch bgp metrics: from RouterOS device: no such command prefix","level":"error","msg":"failed to collect feature metrics","time":"2022-08-01T21:13:42Z"}`

Routeros 7 have new syntax
[admin@MikroTik] > /routing bgp connection
`Flags: D - dynamic, X - disabled, I - inactive

 0 X  name="K8s_new"
     remote.address=172.16.30.0/24 .as=65005
     local.default-address=172.16.30.1 .role=ebgp
     listen=yes routing-table=main as=65001 keepalive-time=1s
[admin@MikroTik] > /routing/bgp/session/print
Flags: E - established
 0   remote.address=172.16.30.228 .refused-cap-opt=no
     local.address=172.16.30.1

 1 E remote.address=172.16.30.229 .as=65005 .id=172.16.30.229 .refused-cap-opt=no .capabilities=mp,as4 .afi=ip,ipv6
     .hold-time=1m30s .messages=40991 .bytes=791923 .eor=""
     local.address=172.16.30.1 .as=65001 .id=192.168.214.1 .capabilities=mp,rr,gr,as4 .messages=1209307 .bytes=22998501
     .eor=""
     output.procid=70 .last-notification=ffffffffffffffffffffffffffffffff0015030400
     input.procid=70 ebgp
     hold-time=1m30s keepalive-time=1s uptime=1w6d23h55m17s350ms

 2 E remote.address=172.16.30.227 .as=65005 .id=172.16.30.227 .refused-cap-opt=no .capabilities=mp,as4 .afi=ip,ipv6
     .hold-time=1m30s .messages=40821 .bytes=785387 .eor=""
     local.address=172.16.30.1 .as=65001 .id=192.168.214.1 .capabilities=mp,rr,gr,as4 .messages=1209335 .bytes=23001809
     .eor=""
     output.procid=72
     input.procid=72 ebgp
     hold-time=1m30s keepalive-time=1s uptime=1w6d23h54m36s540ms

 3 E remote.address=172.16.30.230 .as=65005 .id=172.16.30.230 .refused-cap-opt=no .capabilities=mp,as4 .afi=ip,ipv6
     .hold-time=1m30s .messages=40892 .bytes=788155 .eor=""
     local.address=172.16.30.1 .as=65001 .id=192.168.214.1 .capabilities=mp,rr,gr,as4 .messages=1209320 .bytes=23002003
     .eor=""
     output.procid=71
     input.procid=71 ebgp
     hold-time=1m30s keepalive-time=1s uptime=1w6d23h54m57s630ms`

**Comment by oGi4i** [comment]
@MGlants I've managed to fix the metrics but with some breaking changes to their names and labels (thx Mikrotik for breaking stuff again).
Tested it on my CHR ROS 7.6
